export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
debugger
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
